#!/bin/bash

deps="libqt4-dev libjasper-dev"
py_deps="vidgear opencv-python paho-mqtt readchar inputs"

function is_installed() {
    dpkg -l | grep "$1"
    return $?
}

function install_ultrasonic() {
    pushd /tmp
    echo "INSTALLING ultrasonic"
    git clone https://github.com/GretaThunbergUltras/ultrasonic
    cd ultrasonic
    sudo chmod +x ./install
    sudo ./install
    popd
}

for dep in $deps; do
    echo "INSTALLING $dep"
    if [[ ! $(is_installed $dep) ]]; then
        sudo apt-get install $dep -y &>/dev/null
    fi
done

for py_dep in $py_deps; do
    echo "INSTALLING $py_dep"
    sudo pip3 install $py_dep &>/dev/null
done

install_ultrasonic

# install this library
echo "INSTALLING botlib"
sudo pip3 install . --upgrade &>/dev/null

echo "done."
